// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5oSx4Pb1LSX_vmGw-H0cZp_tQLWR7IM',
    appId: '1:598149250322:web:a5e5dbff246fe6a8bb87cb',
    messagingSenderId: '598149250322',
    projectId: 'lab3-201049',
    authDomain: 'lab3-201049.firebaseapp.com',
    storageBucket: 'lab3-201049.firebasestorage.app',
    measurementId: 'G-X62Z9JZR8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXDw5jEx6TgGMyJpG_LSHwZ1QAkna7mg',
    appId: '1:598149250322:android:4457eb1c050da348bb87cb',
    messagingSenderId: '598149250322',
    projectId: 'lab3-201049',
    storageBucket: 'lab3-201049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt2Ev5aoS55UL-nZ_VHILB6xdCgOwb8OI',
    appId: '1:598149250322:ios:1ada13e818cc5826bb87cb',
    messagingSenderId: '598149250322',
    projectId: 'lab3-201049',
    storageBucket: 'lab3-201049.firebasestorage.app',
    iosBundleId: 'com.example.lab2StefanMladenov201049',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt2Ev5aoS55UL-nZ_VHILB6xdCgOwb8OI',
    appId: '1:598149250322:ios:1ada13e818cc5826bb87cb',
    messagingSenderId: '598149250322',
    projectId: 'lab3-201049',
    storageBucket: 'lab3-201049.firebasestorage.app',
    iosBundleId: 'com.example.lab2StefanMladenov201049',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw5oSx4Pb1LSX_vmGw-H0cZp_tQLWR7IM',
    appId: '1:598149250322:web:f02ca97900ac280bbb87cb',
    messagingSenderId: '598149250322',
    projectId: 'lab3-201049',
    authDomain: 'lab3-201049.firebaseapp.com',
    storageBucket: 'lab3-201049.firebasestorage.app',
    measurementId: 'G-5M8ELC9MVS',
  );
}
